CREATE TABLE `Role` (
  `roleID`    INT UNSIGNED NOT NULL	AUTO_INCREMENT
  `name`      VARCHAR(64) NOT NULL

	PRIMARY KEY (`roleID`)
)
	ENGINE=InnoDB
	AUTO_INCREMENT=1
	DEFAULT	CHARSET=utf8
	COMMENT='Role table';

CREATE TABLE `Privilege` (
  `privilegeID` INT UNSIGNED NOT NULL	AUTO_INCREMENT
  `name`        VARCHAR(64) NOT NULL

	PRIMARY KEY (`privilegeID`)
)
	ENGINE=InnoDB
	AUTO_INCREMENT=1
	DEFAULT	CHARSET=utf8
	COMMENT='Privilege table';

CREATE TABLE `RolePrivilege` (
  `roleID`      INT UNSIGNED NOT NULL	AUTO_INCREMENT,
  `privilegeID` INT UNSIGNED NOT NULL	AUTO_INCREMENT
)
  ENGINE=InnoDB
	AUTO_INCREMENT=1
	DEFAULT	CHARSET=utf8
	COMMENT='Roles and Privileges table';